package JAVA_HOMEWORK;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;

public class CreateEmployeeTables {

    public static void main(String[] args) {
        String DB_URL = "jdbc:oracle:thin:@//localhost:1522/orcl";
        String DB_USER = "system";
        String DB_PASSWORD = "12345";

        // creating tables
        // Creating USERS table
        String userTable = "CREATE TABLE JAVA_USER ("
                + "ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                + "USER_NAME VARCHAR2(50) NOT NULL UNIQUE, "
                + "USER_PASSWORD VARCHAR2(100) NOT NULL, "
                + "STATUS CHAR(1) NOT NULL CHECK (STATUS IN ('E', 'D'))"
                + ")";

        // Creating EMPLOYEE table
        String e_employeeTable = "CREATE TABLE JAVA_EMPLOYEE ("
                + "EMPLOYEE_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                + "FIRST_NAME VARCHAR2(50) NOT NULL, "
                + "LAST_NAME VARCHAR2(50) NOT NULL, "
                + "AGE NUMBER(3,0) NOT NULL, "
                + "MOBILE_PHONE VARCHAR2(20) NOT NULL, "
                + "EMAIL VARCHAR2(100) UNIQUE, "
                + "SOCIAL_SEC_NO VARCHAR2(20) NOT NULL UNIQUE, "
                + "GENDER VARCHAR2(10) NOT NULL, "
                + "DEPARTMENT VARCHAR2(50) NOT NULL, "
                + "HOBBIES VARCHAR2(255)"
                + ")";

        // Creating SALARY_DATA table
        String e_salaryTable = "CREATE TABLE EMP_SALARY ("
                + "SALARY_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                + "EMPLOYEE_ID NUMBER NOT NULL, "
                + "BASIC_SALARY NUMBER(10,2) NOT NULL, "
                + "ALLOWANCE NUMBER(10,2) NOT NULL, "
                + "DEDUCTIONS NUMBER(10,2) NOT NULL, "
                + "GROSS_SALARY NUMBER(10,2) NOT NULL, "
                + "NET_SALARY NUMBER(10,2) NOT NULL, "
                + "FOREIGN KEY (EMPLOYEE_ID) REFERENCES JAVA_EMPLOYEE(EMPLOYEE_ID) ON DELETE CASCADE"
                + ")";

        // Execute the table creation queries
        try (Connection con = DriverManager.getConnection(DB_URL, DB_USER, DB_PASSWORD);
             PreparedStatement stmt1 = con.prepareStatement(userTable);
             PreparedStatement stmt2 = con.prepareStatement(e_employeeTable);
             PreparedStatement stmt3 = con.prepareStatement(e_salaryTable)) {

            stmt1.executeUpdate();
            stmt2.executeUpdate();
            stmt3.executeUpdate();
            System.out.println("Tables created successfully!");

        } catch (SQLException e) {
            e.printStackTrace();
        }



    }
}
